# Site settings
title: Hello Friend
description: Welcome to my blog, wish you have a good time here! Live and learn!
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://blog.pressed.top" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

  # 按时间逆序排列 终于给爷找到了！！
  sort_reverse: true

highlighter: rouge

# Social
facebook: facebook
twitter: twitter
github:  838239178

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy
tagsPage: tags

permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  auto_ids: true
  input: GFM

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: 838239178 #github username
repo: 838239178.github.io #github repository
branch: main #branch
relative_source: ../hanuman/ #source directory
destination: ./build #destination directory
production_url:  https://blog.pressed.top/
source_url:  https://github.com/838239178/838239178.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml