name: Jekyll site deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    
    - name: Build & Deploy to GitHub Pages
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
      uses: BryanSchuetz/jekyll-deploy-gh-pages@master
