name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - uses: ruby/setup-ruby@1.64.1
    
    - run: |
        gem install jekyll
    
    - run: |
        cd /clean && bundle install
        
