name: Jekyll site deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup pythoon
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          architecture: 'x64' 
      - run: pip3 install requests  

      - name: rename posts and push page to baidu
        run: |
          python3 rename.py
          python3 push2baidu.py
      
      - name: Build & Deploy to GitHub Pages
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
