name: Jekyll site deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    with:
      python-version: '3.7' 
      architecture: 'x64'   

    - name: rename posts
      run: python3 rename.py
    
    - name: Build & Deploy to GitHub Pages
      env: 
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
      uses: BryanSchuetz/jekyll-deploy-gh-pages@master
